require("Compatibilities.MetalStars_Vesta.Subgrupe")
require("Compatibilities.Tellus.NextUpgrade")
require("Compatibilities.DiaDie.DiaDieHidingDisablingModContent")
require("Compatibilities.Linox.LinoxHidingDisablingModContent")
require("Compatibilities.Lignumis.LignumisDisabling")
require("Compatibilities.K2_K2SO.K2SO")
require("prototypes.Misc.VanillaHidingDisablingFunction")
require("Compatibilities.Bobs.BobRecipesFixes")