require("Compatibilities.MetalStars_Vesta.MetalStars_Vesta_Updates")
require("Compatibilities.MetalStars_Vesta.MetalStars_Vesta_Recipes")
require("Compatibilities.MetalStars_Vesta.MetalStars_Vesta_Tech")
require("Compatibilities.Bobs.BobsDisabling")
require("Compatibilities.Bobs.BobRecipes")
require("Compatibilities.Bobs.BobTech")
require("Compatibilities.Bobs.Misc")